"""001_add_provenance_and_ingestion_schema

Revision ID: c1d3023a21b1
Revises: None
Create Date: 2026-07-23 11:03:04.143018

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d3023a21b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('product_family', sa.String(length=150), nullable=True))
    op.add_column('products', sa.Column('model', sa.String(length=150), nullable=True))
    op.add_column('products', sa.Column('variant_key', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('source_type', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('source_reference', sa.String(length=550), nullable=True))
    op.add_column('products', sa.Column('discovery_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('products', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('identity_verified', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('spec_verified', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('image_verified', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('price_verified', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('verification_status', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('confidence_level', sa.Numeric(precision=3, scale=2), nullable=False))
    op.add_column('products', sa.Column('spec_coverage', sa.Numeric(precision=3, scale=2), nullable=False))
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('image_match_level', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('ingestion_status', sa.String(length=50), nullable=False))
    op.create_index('idx_products_cat_active_elig', 'products', ['category', 'is_active', 'ingestion_status', 'source_type'], unique=False)
    op.create_index('idx_products_price_lookup', 'products', ['category', 'price_inr'], unique=False)
    op.create_index('idx_products_variant_dedup', 'products', ['brand', 'product_family', 'variant_key'], unique=False)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_ingestion_status'), 'products', ['ingestion_status'], unique=False)
    op.create_index(op.f('ix_products_model'), 'products', ['model'], unique=False)
    op.create_index(op.f('ix_products_product_family'), 'products', ['product_family'], unique=False)
    op.create_index(op.f('ix_products_source_type'), 'products', ['source_type'], unique=False)
    op.create_index(op.f('ix_products_variant_key'), 'products', ['variant_key'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_variant_key'), table_name='products')
    op.drop_index(op.f('ix_products_source_type'), table_name='products')
    op.drop_index(op.f('ix_products_product_family'), table_name='products')
    op.drop_index(op.f('ix_products_model'), table_name='products')
    op.drop_index(op.f('ix_products_ingestion_status'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_index('idx_products_variant_dedup', table_name='products')
    op.drop_index('idx_products_price_lookup', table_name='products')
    op.drop_index('idx_products_cat_active_elig', table_name='products')
    op.drop_column('products', 'ingestion_status')
    op.drop_column('products', 'image_match_level')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'spec_coverage')
    op.drop_column('products', 'confidence_level')
    op.drop_column('products', 'verification_status')
    op.drop_column('products', 'price_verified')
    op.drop_column('products', 'image_verified')
    op.drop_column('products', 'spec_verified')
    op.drop_column('products', 'identity_verified')
    op.drop_column('products', 'last_verified_at')
    op.drop_column('products', 'discovery_timestamp')
    op.drop_column('products', 'source_reference')
    op.drop_column('products', 'source_type')
    op.drop_column('products', 'variant_key')
    op.drop_column('products', 'model')
    op.drop_column('products', 'product_family')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
